# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfcb694a42722cc51e0b8235505f1404bd4f3eb119352c8f31147bb6213e7dae43ee997a1e591f0ddad9bea8ea5093240028b52f8de56842ea3ee432150e8e9b
  secret_token: dummy_variable

test:
  secret_key_base: aa9af9ef1a3f4c77e9226b40f139661b9834f22ab3cc3223b97851278d1f8117fcdd92ca3fa6360176344f32b107263edfeea0ba546090fb6c68574de723273b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
